### ISSUE TITLE
Logo Organisasinya Mana?

### ISSUE THREAD

**Issue by Abdillah** [technocorner/Technocorner2017#1]
Ada satu bug yang menganggu hidup: organisasi GitHub Technocorner ndak ada logonya 😞 
LOL 🤣 
<img width="279" alt="screen shot 2017-04-29 at 8 18 28 pm" src="https://cloud.githubusercontent.com/assets/3030950/25555763/0c3c6794-2d19-11e7-81b3-3364d5791536.png">

**Comment by adhikasp** [comment]
Sudah ada sekarang 👍 
![image](https://cloud.githubusercontent.com/assets/6151302/25796179/b7c05b44-3402-11e7-9cbd-71055914cdc1.png)
Thanks to... whoever update this.
